### ISSUE TITLE
[FR] RSS feed

### ISSUE THREAD

**Issue by TomW1605** [HakierGrzonzo/mma#1]
do you think it would be practical to add an RSS feed to this? there seems to be a well used node rss feed generator and it should be fairly easy to add it in. if you would be open to a PR i would love to give it a shot

**Comment by HakierGrzonzo** [comment]
Will investigate how to add it to the architecture of the app.

**Comment by HakierGrzonzo** [comment]
@TomW1605 I have created a prototype of the RSS feed, should be available [here](https://moringmark.grzegorzkoperwas.site/feed.xml)

Will have to find a place for the icon somewhere in the site tho.

As for PR, feel free to further refine the current RSS file generation under https://github.com/HakierGrzonzo/mma/blob/master/front/app/feed.xml/route.ts (adding the icon with the RSS link somewhere where RSS users expect it would be nice too, I am no RSS user)

If you are unable to run the scraper part, as it requires reddit API access and AWS, just extract [this zip file](https://github.com/user-attachments/files/15817483/results.zip) to `./scraper/results` (or [here](https://github.com/HakierGrzonzo/mma/blob/master/front/public/images) if the symlinks don't work for you)

**Comment by TomW1605** [comment]
i have had a look, and i think it would work best for most RSS viewers if the images were in the description. that field is rendered as HTML so if you put the images in there in img tags they will render in the viewer. i tried to get this to work with react components but ended up just building the HTML as a string

```js
let description = ""
Object.values(comic.images).forEach((img) => {
  description += '<img src="'+getImageUrl(img)+'" alt="'+img.ocr+'" width="'+img.width+'" height="'+img.height+'" />'
})
```

another thing is that RSS readers to not handle when items in the feed change very well. this might cause issues with the series structure. i dont know your data structure well enough, would it be practical to always have a single item per comic even if it is in a series?

**Comment by HakierGrzonzo** [comment]
> if you could put a series on the zip you linked that would help me work out the data struct better

@TomW1605 You can access those json files from a different domain [like so](http://img.moringmark.grzegorzkoperwas.site/index.json). Will try to prepare a more representative test cases later.

As for the structure, the schema for it is defined twice, [once for python](https://github.com/HakierGrzonzo/mma/blob/f23debd6e023e880f9adbf98a0b6f4ca7d2cb3dd/scraper/src/metadata/__init__.py#L17-L50) and [once for typescript](https://github.com/HakierGrzonzo/mma/blob/f23debd6e023e880f9adbf98a0b6f4ca7d2cb3dd/front/utils.ts#L5-L30).

> i tried to get this to work with react components but ended up just building the HTML as a string

Have you tried rendering the components to a string using [renderToString](https://react.dev/reference/react-dom/server/renderToString)? You can also open a draft PR with your current code, I could give you some suggestions more easily.

Also we should be probably adding individual comics (AKA reddit posts) to the RSS instead of series, since that way we could always link the latest episode, will have to think about it tomorrow.

**Comment by TomW1605** [comment]
> @TomW1605 You can access those json files from a different domain [like so](http://img.moringmark.grzegorzkoperwas.site/index.json). Will try to prepare a more representative test cases later.

thanks.



> As for the structure, the schema for it is defined twice, [once for python](https://github.com/HakierGrzonzo/mma/blob/f23debd6e023e880f9adbf98a0b6f4ca7d2cb3dd/scraper/src/metadata/__init__.py#L17-L50) and [once for typescript](https://github.com/HakierGrzonzo/mma/blob/f23debd6e023e880f9adbf98a0b6f4ca7d2cb3dd/front/utils.ts#L5-L30).

cool, i think i can work with that to do per comic not per series



> Have you tried rendering the components to a string using [renderToString](https://react.dev/reference/react-dom/server/renderToString)?

i tried that but react kept complaining and since its a fairly simple bit of html i decided that doing it by hand was easier
![image](https://github.com/HakierGrzonzo/mma/assets/17092573/ae8ea852-8076-4b6d-b588-be2f45b95367)


> You can also open a draft PR with your current code, I could give you some suggestions more easily.

will do

**Comment by HakierGrzonzo** [comment]
@TomW1605 You might be intrested in this hack https://github.com/vercel/next.js/issues/43810#issuecomment-1623723535

Works well in this case:
```diff
diff --git a/front/app/feed.xml/route.ts b/front/app/feed.xml/route.tsx
similarity index 88%
rename from front/app/feed.xml/route.ts
rename to front/app/feed.xml/route.tsx
index a55e3e6..b46aaf1 100644
--- a/front/app/feed.xml/route.ts
+++ b/front/app/feed.xml/route.tsx
@@ -1,9 +1,11 @@
+
 import { PAGE_URL } from "@/constants";
 import { useComicMetadata } from "@/hooks";
 import { getAllMetadata, getImageUrl } from "@/utils";
 import RSS from "rss";

 export async function GET() {
+  const { renderToString } = await import('react-dom/server')
   const feed = new RSS({
     title: "MoringMarkArchive",
     feed_url: `${PAGE_URL}/feed.xml`,
@@ -20,9 +22,10 @@ export async function GET() {
     const firstImage = comic.images[firstImageLink];
     const articleImageLink = getImageUrl(firstImage);
     const description = firstImage.ocr || "A Comic";
+    const descriptionHtml = renderToString(<p>{description}</p>)
     feed.item({
       title: comic.series.title,
-      description,
+      description: descriptionHtml,
       url: `${PAGE_URL}/comic/${comic.series.id}`,
       categories: [],
       author: "u/makmark",
```

![image](https://github.com/HakierGrzonzo/mma/assets/36668331/c361e27e-f86d-45fd-b93a-f2a638e55731)

**Comment by TomW1605** [comment]
oh, thats a neat workaround. it seems to work at the input stage but i get more errors later on. i think given that this should be a basic html thing anyway its not worth the hassle to not just build it as a string. unless you have a particular reason not to do that?

**Comment by TomW1605** [comment]
made a PR with my changes

**Comment by HakierGrzonzo** [comment]
Issue will be closed after I add the RSS button somewhere

**Comment by TomW1605** [comment]
for the sake of simplicity, i would just stick another line under the main page description that is something like

"An RSS feed can be found [here](https://moringmark.grzegorzkoperwas.site/feed.xml)"

also, one other thing i forgot to mention. i have limited the feed to the most recent 30 submitions. that was more just for testing. i think since readers dont load the images till you open the item and since the limiting is doen *after* all the sorting, there isnt much point in doing this long term.

**Comment by HakierGrzonzo** [comment]
> i have limited the feed to the most recent 30 submitions. that was more just for testing

I will leave it with the limit, with 800+ comics the file size of the feed would only grow and the current size is good enough to get notifications for new releases

**Comment by TomW1605** [comment]
fair enough
