### ISSUE TITLE
add reddit link to rss feed

### ISSUE THREAD

**Issue by TomW1605** [HakierGrzonzo/mma#4]
just thought it might be worth adding a link to the origonal reddit post to the rss feed

think the easiest way to do this is to stick 
```
description += `<p><a href="${comic.link}">Origonal Post</a></p>\`;
```
after the loop that adds the images

i think at the bottom is better since that is where people will be when they want to go to the reddit post (ie, to read comments)

i dont think it should be the main link since that is used to link to spesific points in a series as well and this site is a better interface for looking at a series that reddit.

**Comment by HakierGrzonzo** [comment]
@TomW1605 

We could do that, but then our RSS description starts to grow in complexity and starts being a copy of the current `/comic/*` pages, which is not really what the standard wants from us.

See the [rss specification](https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt) for the description field, which states that it is supposed to be `The item synopsis.`, not the whole item.

**Comment by TomW1605** [comment]
thats fair, but remember, RSS was designed for blogs and news sites. so "the whole thing" would be a hundreds of words long news article or blog. i think in this case adding just the reddit link isnt increasing the complexity that much, and it is still extremely simple compared to the comic pages on the site.

i think in this case the RSS spec should be seen as more of a guide. it is generally seen as a very flexable spec, remember podcasts are also technically RSS feeds

it will also save people having to click through to your site and since your not running ads that will not cost you anything and saves you server resources

**Comment by HakierGrzonzo** [comment]
That's fair, you may, proceed with development if yoy want, but I would prefer if it used react to render the description, since the current setup reminds me of my jquery days

**Comment by TomW1605** [comment]
lol, fair. ill have another go at getting it working with renderToString but it probably wont be for a bit. got a busy weekend coming up

**Comment by TomW1605** [comment]
ok, got it working with renderToString, i think i just needed to change the file name so it could handle the inline elements right
